version: '3.8'

services:
  vault:
    image: vault:1.15.0
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: "http://localhost:8200"
    cap_add:
      - IPC_LOCK
    command: server -dev -dev-root-token-id=myroot
    volumes:
      - ./vault/data:/vault/data
      - ./vault/config:/vault/config
    networks:
      - vault-network

  vault-ui:
    image: docker.io/hashicorp/vault-ui:latest
    container_name: vault-ui
    ports:
      - "8000:8000"
    environment:
      VAULT_URL: "http://vault:8200"
      VAULT_TOKEN: "myroot"
    depends_on:
      - vault
    networks:
      - vault-network

networks:
  vault-network:
    driver: bridge